env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: [ ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  no-case-declarations: off
  no-irregular-whitespace: off
  indent: off
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-restricted-syntax:
    - error
    - selector: TSEnumDeclaration,
      message: "不要用 Enum"