version: "3"
services:
  backend:
    restart: always
    build: .
    image: t1fr/smsb
    container_name: squadron-management-backend
    environment:
      NODE_ENV: production
    ports:
      - "6518:6518"