import type { Enum } from "@t1fr/backend/ddd-types";

export const Country = {
    England: "country_britain",
    Sweden: "country_sweden",
    Italy: "country_italy",
    USA: "country_usa",
    ModernUSA: "country_usa_modern",
    China: "country_china",
    USSR: "country_ussr",
    Germany: "country_germany",
    Lithuania: "country_lithuania",
    WeimarGermany: "country_germany_weimar_republic",
    Japan: "country_japan",
    France: "country_france",
    Israel: "country_israel",
    Austria: "country_austria",
    India: "country_india",
    Slovakia: "country_slovakia",
    Spain: "country_spain",
    RepublicChina: "country_republic_china",
    Bangladesh: "country_bangladesh",
    Norway: "country_norway",
    Egypt: "country_egypt",
    ModernSouthAfrica: "country_south_africa_modern",
    NorthKorea: "country_north_korea",
    GermanyEmpireNavy: "country_germany_empire_navy",
    ModernJapan: "country_japan_modern",
    Jordan: "country_jordan",
    Cuba: "country_cuba",
    Argentina: "country_argentina",
    Czech: "country_czech",
    NewZealand: "country_new_zealand",
    Kazakhstan: "country_kazakhstan",
    Syria: "country_syria",
    Pakistan: "country_pakistan",
    Russia: "country_russia",
    Hungary: "country_hungary",
    BritainEmpireNavy: "country_britain_empire_navy",
    SouthVietnamNavy: "country_south_vietnam_navy",
    ModernGreece: "country_greece_modern",
    ModernGermany: "country_germany_modern",
    Ireland: "country_ireland",
    Portugal: "country_portugal",
    SaudiArabia: "country_saudi_arabia",
    ModernCanada: "country_canada_modern",
    RussiaEmpireNavy: "country_russia_empire_navy",
    GDR: "country_gdr",
    Canada: "country_canada",
    Poland: "country_poland",
    ItalyKingdom: "country_italy_kingdom",
    Invisible: "country_invisible",
    Philippines: "country_philippines",
    Vietnam: "country_vietnam",
    Australia: "country_australia",
    SouthAfrica: "country_south_africa",
    Switzerland: "country_switzerland",
    Finland: "country_finland",
    Turkey: "country_turkey",
    Romania: "country_romania",
    ModernHungary: "country_hungary_modern"
} as const;

export type Country = Enum<typeof Country>;