bot:
  roles:
    core_player: "1046629026355228762"
    casual_player: "1103384315599015987"
    squad_battle: "1054766361991204864"

crawler:
  urls:
    squad_account_list: "https://warthunder.com/en/community/claninfo/The%20First%20Frontline%20Rangers"
