/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountTypeSelection: typeof import('./../src/components/AccountTypeSelection.vue')['default']
    ArticleSection: typeof import('./../src/components/ArticleSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ExternalLink: typeof import('./../src/components/ExternalLink.vue')['default']
    MdiAlert: typeof import('~icons/mdi/alert')['default']
    MdiCheckboxMarkedCircleOutline: typeof import('~icons/mdi/checkbox-marked-circle-outline')['default']
    MdiChevronDoubleDown: typeof import('~icons/mdi/chevron-double-down')['default']
    MdiDelete: typeof import('~icons/mdi/delete')['default']
    MdiDiscord: typeof import('~icons/mdi/discord')['default']
    MdiExclamationThick: typeof import('~icons/mdi/exclamation-thick')['default']
    MdiLogin: typeof import('~icons/mdi/login')['default']
    MdiLogout: typeof import('~icons/mdi/logout')['default']
    MdiPause: typeof import('~icons/mdi/pause')['default']
    MdiRecord: typeof import('~icons/mdi/record')['default']
    MdiUpload: typeof import('~icons/mdi/upload')['default']
    MdiYoutube: typeof import('~icons/mdi/youtube')['default']
    MemberPanel: typeof import('./../src/components/MemberPanel.vue')['default']
    MembersDropdown: typeof import('./../src/components/MembersDropdown.vue')['default']
    MemberSnippet: typeof import('./../src/components/MemberSnippet.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    PieChart: typeof import('./../src/components/PieChart.vue')['default']
    PointMeter: typeof import('./../src/components/PointMeter.vue')['default']
    PointTypeSelection: typeof import('./../src/components/PointTypeSelection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SQBBadgeGalleryItem: typeof import('./../src/components/SQBBadgeGalleryItem.vue')['default']
    SquadMedalCarousel: typeof import('./../src/components/SquadMedalCarousel.vue')['default']
    SummaryDisplay: typeof import('./../src/components/SummaryDisplay.vue')['default']
    TopNavigationBar: typeof import('./../src/components/TopNavigationBar.vue')['default']
  }
}
