/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountTypeSelection: typeof import('./../src/components/AccountTypeSelection.vue')['default']
    ArticleSection: typeof import('./../src/components/ArticleSection.vue')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    ExternalLink: typeof import('./../src/components/ExternalLink.vue')['default']
    Knob: typeof import('primevue/knob')['default']
    MdiDiscord: typeof import('~icons/mdi/discord')['default']
    MdiHome: typeof import('~icons/mdi/home')['default']
    MdiYoutube: typeof import('~icons/mdi/youtube')['default']
    MemberPanel: typeof import('./../src/components/MemberPanel.vue')['default']
    MembersDropdown: typeof import('./../src/components/MembersDropdown.vue')['default']
    MemberSnippet: typeof import('./../src/components/MemberSnippet.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    PieChart: typeof import('./../src/components/PieChart.vue')['default']
    PointMeter: typeof import('./../src/components/PointMeter.vue')['default']
    PointTypeSelection: typeof import('./../src/components/PointTypeSelection.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    SQBBadgeGalleryItem: typeof import('./../src/components/SQBBadgeGalleryItem.vue')['default']
    SquadMedalCarousel: typeof import('./../src/components/SquadMedalCarousel.vue')['default']
    SummaryDisplay: typeof import('./../src/components/SummaryDisplay.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    TopNavigationBar: typeof import('./../src/components/TopNavigationBar.vue')['default']
  }
}
