/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/accounts': RouteRecordInfo<'/admin/accounts', '/admin/accounts', Record<never, never>, Record<never, never>>,
    '/admin/members': RouteRecordInfo<'/admin/members', '/admin/members', Record<never, never>, Record<never, never>>,
    '/admin/points': RouteRecordInfo<'/admin/points', '/admin/points', Record<never, never>, Record<never, never>>,
    '/me': RouteRecordInfo<'/me', '/me', Record<never, never>, Record<never, never>>,
    '/me/dashboard': RouteRecordInfo<'/me/dashboard', '/me/dashboard', Record<never, never>, Record<never, never>>,
    '/redirect': RouteRecordInfo<'/redirect', '/redirect', Record<never, never>, Record<never, never>>,
    '/squadron-battle': RouteRecordInfo<'/squadron-battle', '/squadron-battle', Record<never, never>, Record<never, never>>,
    '/squadron-battle/metalist': RouteRecordInfo<'/squadron-battle/metalist', '/squadron-battle/metalist', Record<never, never>, Record<never, never>>,
    '/squadron-battle/overview': RouteRecordInfo<'/squadron-battle/overview', '/squadron-battle/overview', Record<never, never>, Record<never, never>>,
    '/squadron-battle/record': RouteRecordInfo<'/squadron-battle/record', '/squadron-battle/record', Record<never, never>, Record<never, never>>,
    '/squadron-battle/search': RouteRecordInfo<'/squadron-battle/search', '/squadron-battle/search', Record<never, never>, Record<never, never>>,
  }
}
