name: setup-env
description: "設置環境"
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v4
          with:
              fetch-depth: 0
        - uses: pnpm/action-setup@v3
        - uses: actions/setup-node@v4
          with:
              node-version: 20
              cache: "pnpm"
        - run: pnpm install --frozen-lockfile
        - name: 設定 NX affected 所需要的 base 跟 main 變數
          uses: nrwl/nx-set-shas@v4

        # 讓 CI 在 PR 時可以正常作用，必須執行
        - run: git branch --track main origin/main
          if: ${{ github.event_name == 'pull_request' }}
