name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    name: Build Docker image and push to github container registry
    runs-on: ubuntu-latest
    steps:
      - name: Login Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/t1fr/squadron-manager:latest

  deploy:
    name: Deploy image to KCL Server
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Login Github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker pull ghcr.io/t1fr/squadron-manager:latest
      - run: docker stop squadron-management-backend
      - run: docker rm squadron-management-backend
      - run: docker run -itd --name squadron-management-backend -p 6518:6518 --restart unless-stopped -e NODE_ENV=production ghcr.io/t1fr/squadron-manager:latest