name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3.0.0
    - name: compose up
      run: docker-compose up --build --force-recreate --no-deps -d backend
      shell: cmd
