name: Remove PR preview site on merged, closed
on:
    pull_request:
        types:
            - closed
env:
    SUBROUTE: "t1fr-pr${{github.event.pull_request.number}}-${{github.event.pull_request.head.ref}}"
jobs:
    remove:
        runs-on: ubuntu-latest
        steps:
            - name: 移除本次 PR 的預覽用網站
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: 220.135.86.181
                  username: T1FR Server
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: rm -rf ./Documents/services/nginx/sites/${{env.SUBROUTE}}
            - name: 移除有關預覽用網站的 PR 評論
              uses: thollander/actions-comment-pull-request@v2
              with:
                  message: deleting...
                  comment_tag: deploy
                  mode: delete
